### ISSUE TITLE
[Question] Kafka connect with binary avro message

### ISSUE THREAD

**Issue by MarcMagnin** [confluentinc/examples#103]
Hi, 

I wanted to use avro encoded messages within kafka connect but it seems that the message is automatically base64 encoded when creating the `SourceRecord[]` with `Schema.BYTES_SCHEMA`.
When a consumer want to read such message, it fails even if I base64 decode and remove the extra double quotes that are added to the message : `"base64EncodedAvroMessage"`

Any ideas how to make it?
Regards,
Marc

**Comment by ewencp** [comment]
@MarcMagnin What converter settings do you have for `key.converter` and `value.converter` in your worker config? It sounds like you might have the JsonConverter, which would base64 encode binary data since JSON doesn't have a native representation for binary data. See http://docs.confluent.io/current/connect/concepts.html#converters for an explanation of converters.

**Comment by MarcMagnin** [comment]
Thanks for your reply. 
Thanks for pointing me out on the converter of the worker. Effectively it is set to JsonConverter. I can find StringConverter but that's about. Where can I find the dependencies that have BinaryConverter or AvroConverter?

**Comment by miguno** [comment]
@MarcMagnin: By the way, such general usage questions are better asked in the following places:

- The [Confluent mailing list](https://groups.google.com/forum/?pli=1#!forum/confluent-platform) or the [kafka-user mailing list](https://kafka.apache.org/contact).
- The [Confluent Community slack](https://confluentcommunity.slack.com/).  You can register an account for free at https://slackpass.io/confluentcommunity.

**Comment by MarcMagnin** [comment]
Cheers.
