### ISSUE TITLE
Kafka Stream Java Example Application stuck

### ISSUE THREAD

**Issue by ktlim86** [confluentinc/examples#109]
I am new to Kafka and I am running into a problem with an example while I was attempting the tutorial [here][1].

I cannot see the output of the processing in another broker. I modified the code to see what is happening. Somehow the code got stuck and I dont see any `System.out.println` coming from `flatMapValues` method.

Here is the code I have used

    public static void main(final String[] args) throws Exception {
		Properties props = new Properties();
        props.put(StreamsConfig.APPLICATION_ID_CONFIG, "streams-wordcount");
        props.put(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, "EXTERNAL_IP:9092");
        props.put(StreamsConfig.KEY_SERDE_CLASS_CONFIG, Serdes.String().getClass().getName());
        props.put(StreamsConfig.VALUE_SERDE_CLASS_CONFIG, Serdes.String().getClass().getName());

        // setting offset reset to earliest so that we can re-run the demo code with the same pre-loaded data
        // Note: To re-run the demo, you need to use the offset reset tool:
        // https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Streams+Application+Reset+Tool
        props.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");

        KStreamBuilder builder = new KStreamBuilder();

        KStream<String, String> source = builder.stream("streams-file-input");

        KTable<String, Long> counts = source
                .flatMapValues(new ValueMapper<String, Iterable<String>>() {
                    @Override
                    public Iterable<String> apply(String value) {
                    	System.out.println ("value is "+value+".");
                        return Arrays.asList(value.toLowerCase(Locale.getDefault()).split(" "));
                    }
                }).map(new KeyValueMapper<String, String, KeyValue<String, String>>() {
                    @Override
                    public KeyValue<String, String> apply(String key, String value) {
                    	System.out.println ("key is "+key+". value is "+value+".");
                        return new KeyValue<>(value, value);
                    }
                })
                .groupByKey()
                .count("Counts");

        // need to override value serde to Long type
        counts.to(Serdes.String(), Serdes.Long(), "streams-wordcount-output");

        KafkaStreams streams = new KafkaStreams(builder, props);
        streams.start();
        System.out.println ("Started");

        // usually the stream application would be running forever,
        // in this example we just let it run for some time and stop since the input data is finite.
        Thread.sleep(5000L);

        streams.close();
        System.out.println ("Stopped");
	}

I am running this in Eclipse on Windows 10. I could not find where is the problem. Kafka is installed in Ubuntu 16.04 and the version I used is `0.10.2.0-cp1`.

Please advise. Thanks.

  [1]: http://docs.confluent.io/3.2.0/streams/quickstart.html#streams-quickstart

**Comment by miguno** [comment]
First, I'd suggest to ask your question in the Confluent mailing list, since your problem is not related to the example applications of this project (you are working with Apache Kafka's [WordCount example for 0.10.2](https://github.com/apache/kafka/blob/0.10.2/streams/examples/src/main/java/org/apache/kafka/streams/examples/wordcount/WordCountDemo.java)): 
https://github.com/confluentinc/examples/tree/3.2.x/kafka-streams#help

That said, here are some pointers:

- Even though this question might seem odd at first to you:  The problem you are describing, has this happened already on your first run of the application, or only on subsequent runs?

- Did you [pre-create the input topic and the output topic](https://github.com/apache/kafka/blob/0.10.2/streams/examples/src/main/java/org/apache/kafka/streams/examples/wordcount/WordCountDemo.java#L43-L44) for Apache Kafka's WordCount example?  Note that you should also pre-create the output topic, not just the input topic.  I just sent a PR to the Apache Kafka project that clarifies the topic management instructions (https://github.com/apache/kafka/pull/2812), and I also clarified the [Confluent 3.2.0 Quickstart for Kafka Streams](http://docs.confluent.io/3.2.0/streams/quickstart.html#streams-quickstart) similarly.

- While your application is running, you should write some input data to its input topic (for Apache Kafka's WordCount example, the input topic's name is "streams-file-input").  Have you done so?  I'd recommend the following order: (1) build and run your application, and then (2) produce input data to its input topic.  Separately, you can (3) inspect the output data in the output topic, e.g. via the console consumer as described in the [Confluent 3.2.0 Quickstart for Kafka Streams](http://docs.confluent.io/3.2.0/streams/quickstart.html#streams-quickstart).

- Perhaps your problem is due to developing/running your application on Windows 10.  Even though we have been working on improving Windows OS support, most testing is done on Linux and Mac.  Did you spot any errors while running your application that point in this direction?

**Comment by ktlim86** [comment]
@miguno Thank you for your suggestion. I would try it out and see if it works. :)

**Comment by ktlim86** [comment]
@miguno I have posted a question in the [mailing list](https://groups.google.com/forum/#!topic/confluent-platform/DxKkKn2cQBE). Hope to hear from them soon.

Thanks for your help! :)
