### ISSUE TITLE
SpecificAvroDeserializer NullPointerException

### ISSUE THREAD

**Issue by billmag** [confluentinc/examples#20]
Hello-

I'm getting the below when trying to run an example similar to the WikipediaFeedAvroLambdaExample. My build successfully runs the com.commercehub.gradle.plugin:gradle-avro-plugin to generate the org.apache.avro.specific.SpecificRecord for my .avsc file, and everything else seems pretty reasonable. I'm also running the SchemaRegistry from the 2.1.0-alpha download of the Confluent platform.

Do you expect the SpecificAvroDeserializer to work? I get a NullPointerException on "inner", and given that the empty constructor is used and there is nothing that ever seems to set inner, I'm wondering how it's supposed to work at all? I manually registered my Avro schema with the registry via curl, and that worked fine.

The behavior I see is:

At boot:
```
log4j:WARN No appenders could be found for logger (org.apache.kafka.streams.StreamsConfig).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

Then, after I publish my avro encoded message to the topic, I immediately get a NullPointerException. I don't get any stdout output from the SchemaRegistry, so I assume there's no magic causing it to be queried.
```
Exception in thread "StreamThread-1" java.lang.NullPointerException
	at io.confluent.examples.streams.utils.SpecificAvroDeserializer.deserialize(SpecificAvroDeserializer.java:51)
	at io.confluent.examples.streams.utils.SpecificAvroDeserializer.deserialize(SpecificAvroDeserializer.java:24)
	at org.apache.kafka.streams.processor.internals.SourceNode.deserializeValue(SourceNode.java:41)
	at org.apache.kafka.streams.processor.internals.RecordQueue.addRawRecords(RecordQueue.java:77)
	at org.apache.kafka.streams.processor.internals.PartitionGroup.addRawRecords(PartitionGroup.java:113)
	at org.apache.kafka.streams.processor.internals.StreamTask.addRecords(StreamTask.java:134)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:334)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:248)

Process finished with exit code 0
```

It would be good to know if the answer is just to wait for a later release of kafka-streaming, or if I should go about trying to get this to work (or pursue a different deserialization method)?

**Comment by miguno** [comment]
@guozhangwang : I think you already took a look at this, want to chime in?

**Comment by miguno** [comment]
@billmag : I think the root problem is that the example you are referring to (`WikipediaFeedAvroLambdaExample`) does not show yet how to run and integrate with the Confluent [Avro schema-registry](https://github.com/confluentinc/schema-registry) ([docs](http://docs.confluent.io/2.1.0-alpha1/schema-registry/docs/index.html)) 100% end-to-end, thus you run into these Avro-related errors at run-time.

Background: The Avro serdes under [utils/](https://github.com/confluentinc/examples/tree/master/kafka-streams/src/main/java/io/confluent/examples/streams/utils) require (1) a running schema registry and (2) might need ("might" because I gave it a quick check only) some code updates to integrate with said schema registry (e.g. the configuration setting that specifies under which URL the schema registry is running, see [Java Applications: Serializers](http://docs.confluent.io/2.1.0-alpha1/app-development.html#java-applications-serializers).

**Comment by billmag** [comment]
Thanks for the thoughts -- it does seem like some code is missing. I'm running a schema registry and things seem fine on that side.

Do you have any idea when a more complete code sample will be available? I'm not in a huge rush to get this code working (it's a side project right now), so if it's already in the works to be released it's not a big deal.

**Comment by miguno** [comment]
@billmag: You could try the following in the meantime.

Background: Some examples such as `WikipediaFeedAvroLambdaExample` set the Avro ser/deserializers as the default serde via `streamsConfiguration`, and subsequent operations (e.g. `builder.stream(...)` rely on these default serdes.  But there's a problem, example gist:

```java
streamsConfiguration.put(StreamsConfig.VALUE_SERIALIZER_CLASS_CONFIG, SpecificAvroSerializer.class);
streamsConfiguration.put(StreamsConfig.VALUE_DESERIALIZER_CLASS_CONFIG, SpecificAvroDeserializer.class);
```

This `*.class` approach for configuring key/value serdes has the drawback that only the default, non-arg constructors of `SpecificAvroSerializer` etc. are being invoked by Kafka Streams.  However, for proper functioning, the generic+specific Avro serdes require a `SchemaRegistryClient` instance.

So you could try the following in `WikipediaFeedAvroLambdaExample` and then report back here:

```java
// Add:
SchemaRegistryClient client = ...;  // set up as needed
final Serializer<WikiFeed> wikifeedSerializer = new SpecificAvroSerializer<WikiFeed>(client);
final Deserializer<WikiFeed> wikifeedDeserializer = new SpecificAvroDeserializer<WikiFeed>(client);

// Replace...
KStream<String, WikiFeed> feeds = builder.stream("WikipediaFeed");
// ...with
KStream<String, WikiFeed> feeds = builder.stream(stringDeserializer, wikifeedDeserializer, "WikipediaFeed");
```

**Comment by miguno** [comment]
@billmag: You can also try again now with the latest code in `master`.  See the fix in PR https://github.com/confluentinc/examples/issues/23.

**Comment by billmag** [comment]
Saw that, hoping to get some time today. Thank you :)

On Fri, Apr 15, 2016 at 12:25 PM, Michael G. Noll <notifications@github.com>
wrote:

> @billmag <https://github.com/billmag>: You can also try again now with
> the latest code in master. See the fix in PR #23
> <https://github.com/confluentinc/examples/pull/23>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/confluentinc/examples/issues/20#issuecomment-210529396>
>



-- 

Bill Magnuson *|* Co-Founder & CTO | *@billmag*

A people-first conference in the mobile-first era: LTR is coming to SF!
Buy your ticket today <http://ltr.appboy.com/signature>.

**Comment by miguno** [comment]
@billmag:  Since your last feedback we made a couple of improvements in Kafka Streams, which are available in the upcoming Kafka 0.10.0 release (aka Kafka's `0.10.0` branch as of today).

We have also updated the code _in this repo_ to match the upcoming Kafka 0.10.0 release, which you find in the work-in-progress branch https://github.com/confluentinc/examples/tree/kafka-0.10.0.0.  I say "work in progress" because we have been using this branch to follow Kafka's 0.10.0 development work, which is not yet officially released (so further changes might be happening upstream, which might require further work in this repo to stay compatible).

_Note: The code in https://github.com/confluentinc/examples/tree/kafka-0.10.0.0 is not compatible with the Kafka Streams implementation in the Tech Preview (= what you have been using so far)._

Feel free to take a look at:
* [GenericAvroIntegrationTest](https://github.com/confluentinc/examples/blob/kafka-0.10.0.0/kafka-streams/src/test/java/io/confluent/examples/streams/GenericAvroIntegrationTest.java) (in feature branch, not `master`)
* [SpecificAvroIntegrationTest](https://github.com/confluentinc/examples/blob/kafka-0.10.0.0/kafka-streams/src/test/java/io/confluent/examples/streams/SpecificAvroIntegrationTest.java) (in feature branch, not `master`)

**Comment by billmag** [comment]
Thanks @miguno -- I'll try to take a look if I get some time today. The direction looks good.

Any idea when 0.10.0 is releasing?

**Comment by miguno** [comment]
Kafka 0.10.0.0 should be out (fingers crossed) in 1-2 weeks.

**Comment by billmag** [comment]
We can close out this issue since you've probably fixed it and I keep getting pulled in other directions :)

I would like to chat with the appropriate person on your team about plans for the Kafka Streaming beta/rollout/launch partners/etc. as we're considering using it here for a new project but want to get some confidence around it as we'd need to deploy it at heavy scale right out of the gate. I can be contacted at bill at appboy dot com.

**Comment by guozhangwang** [comment]
Hi @billmag , I am the tech lead of Kafka Streams project and would like to invite you to our AskMeAnything (AMA) meeting tomorrow, which is like an office hour via Zoom video chat for any questions you may want so that I can answer, if that works for you.

**Comment by billmag** [comment]
Hey @guozhangwang -- sure, myself or someone on my team can definitely join. Please hit me up via email with more details :)

**Comment by guozhangwang** [comment]
I have forwarded the invitation to your appboy email account.

**Comment by billmag** [comment]
I haven't received the invite yet, can you re send?

**Comment by guozhangwang** [comment]
I have just resend, could you confirm if you have received it?

Just in case, if you install Zoom already, you can join the meeting with this url: https://confluent.zoom.us/j/579243909

The meeting start today at 11am PDT.

**Comment by billmag** [comment]
Yep, I received it. Thanks.

**Comment by dollschasingmen** [comment]
Is there anyway to do avro serialization w/o a schema registry client? currently we are generating `SpecificRecord` using avrohugger and then trying to publish them in the stream using a avro serde constructed like this:

`val avroSerde: Serde[Object] = Serdes.serdeFrom(new KafkaAvroSerializer(), new KafkaAvroDeserializer())`

called 

`asAvroRecord.to(byteArraySerde, avroSerde, "myoutput-topic")`

and this is giving an error

```
   [error] (StreamThread-1) org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: java.lang.NullPointerException
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:72)
	at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:54)
	at org.apache.kafka.streams.processor.internals.RecordCollector.send(RecordCollector.java:77)
```

**Comment by miguno** [comment]
@dollschasingmen : Could you please open a new GH issue for your question?

**Comment by miguno** [comment]
@dollschasingmen: Sorry, hit the Comment button too early.  What I wanted to write was:  Could you please open a new GH issue for your question at https://github.com/confluentinc/schema-registry/issues (which is where we currently maintain the Avro serializers)?

**Comment by dollschasingmen** [comment]
@miguno ah sorry, i moved it to: https://github.com/confluentinc/schema-registry/issues/389

thank you!

**Comment by eliaslevy** [comment]
@dollschasingmen if you want a plain Avro serde, minus schema registry or attaching a schema identifier to serialized data, you can find one [here](https://gist.github.com/eliaslevy/155c72b089b14d54a36038d18272f04c).
