### ISSUE TITLE
KSQL example is broken

### ISSUE THREAD

**Issue by hally9k** [confluentinc/examples#338]
The KSQL persistent streams example in the docs is broken:

https://docs.confluent.io/current/quickstart/ce-docker-quickstart.html#

It says to do `CREATE STREAM pageviews_female AS SELECT users.userid AS userid, pageid, regionid, gender FROM pageviews LEFT JOIN users ON pageviews.userid = users.userid WHERE gender = 'FEMALE';
`

Which to get working I had to change to: `CREATE STREAM pageviews_female AS SELECT users.userid AS userid, pageid, regionid, gender FROM pageviews LEFT JOIN users ON pageviews.userid = users.rowkey WHERE gender = 'FEMALE';
`

Just a heads up about a bit of sales funnel friction for a noob here!

**Comment by ybyzek** [comment]
@hally9k 

1. What is the error generated with `CREATE STREAM pageviews_female AS SELECT users.userid AS userid, pageid, regionid, gender FROM pageviews LEFT JOIN users ON pageviews.userid = users.userid WHERE gender = 'FEMALE';` ?

2. This works: https://github.com/confluentinc/examples/blob/5.3.1-post/cp-quickstart/ksql.commands#L7  

So it's a bit unclear what the issue is.  If you could provide more information, that would be helpful, thanks.

**Comment by hally9k** [comment]
This is the error I get when trying to copy and paste directly from the tutorial:
![image](https://user-images.githubusercontent.com/3803536/68555492-ef9cfa00-0492-11ea-84cf-3031cd83bab6.png)

**Comment by ybyzek** [comment]
@hally9k thanks for the information, this helps!

I have tried but can't reproduce this.  I am letting the engineering team know about this issue, and I hope to get more troubleshooting tips.

**Comment by ybyzek** [comment]
@hally9k thanks to a suggestion from @mikebin , I was able to reproduce the issue.  That error message happens if you create a TABLE without specifying the key, which is a required step in the documentation (See screenshot attached). 

<img width="618" alt="Screen Shot 2019-11-10 at 21 39 52" src="https://user-images.githubusercontent.com/12448600/68557073-b321bd80-0402-11ea-9564-114a1c3c2f58.png">

Please re-run and specify the `key` to be the `userid` field.

**Comment by hally9k** [comment]
@ybyzek  Ah hah! That makes perfect sense. I remember skimming a bit fast over that section, I think that was because all of the other fields in that list are set to those values as a default. Maybe we could highlight the setting of the key a bit more clearly in the instructions to avoid more noob slip ups here.
The tutorial and product came across super polished and awesome otherwis, though. Great project!!! ❤️

**Comment by ybyzek** [comment]
@hally9k 💯 agree.  I filed a jira to improve the documentation, thanks!
