### ISSUE TITLE
guidance on how best to generate scala auto stub classes

### ISSUE THREAD

**Issue by dollschasingmen** [confluentinc/examples#56]
our scala kafka-streams project uses 

https://github.com/sbt/sbt-avro
https://github.com/julianpeeters/sbt-avrohugger

to generate Avro SpecificRecord stub classes. What these plugins do is generate a Java SpecificRecord and then this class  is wrapped in a scala case class.

The problem is that this scala case stub class itself is *not* a SpecificRecord - it merely wraps around one.

The issue is that this won't work with the SpecificAvroSerde which expects `<T extends org.apache.avro.specific.SpecificRecord>`

Not sure what should be done -- would it be a bad idea to remove this constraint? Should there be a scala version of the Avro Serde's that perhaps is unbounded? I have yet to come across a scala avro class generator that generates classes that extend SpecificRecord but will keep on looking.

There are work arounds for this (like adding a step to expose the wrapped up java class) but just raising up this slight impedance mismatch.

**Comment by miguno** [comment]
In one project of mine (https://github.com/miguno/kafka-storm-starter) I have also been using sbt-avro (but not sbt-avrohugger), and here the generation of Avro SpecificRecord stub classes "just works" as expected, i.e. the Scala stub class *is* a `SpecificRecord`.  So I guess in your case the problem is sbt-avrohugger, which introduces case classes / ADTs to the setup (which I understand is desirable, but has the downside of making the Scala stub class not be a `SpecificRecord`).

**Comment by miguno** [comment]
Also, I think ultimately the question (regarding type constraint) is not about the Avro serdes included in the examples repository, but rather the Confluent Avro serializers/deserializers that are used behind the scenes (cf. https://github.com/confluentinc/schema-registry/tree/master/avro-serializer).

**Comment by dollschasingmen** [comment]
yea -- i agree, the bigger issue is how to integrate  a scala kafka-streams application with the serializers/formatters in schema-registry.

so for now, we can probably get away with not using case classes / ADT but would be really nice to have.

closing this because I think my question was answered.
