### ISSUE TITLE
Where are these functions?

### ISSUE THREAD

**Issue by jyeargers** [confluentinc/examples#62]
https://github.com/confluentinc/examples/blob/master/kafka-streams/src/main/java/io/confluent/examples/streams/AnomalyDetectionLambdaExample.java#L140-L147

the .groupbykey() and .count() functions aren't defined in the 0.10.0.1 release (insofar as I can see).

**Comment by miguno** [comment]
You are right.  That's because `AnomalyDetectionLambdaExample` in your link above is from this repository's `master` branch, and thus uses a development version of Kafka (read: a version that is not yet publicly released, unlike 0.10.0.1 release).

Quoting from `kafka-streams/README`:

> **When using the master branch:** The `master` branch typically requires the latest trunk version of Apache Kafka (cf. `kafka.version` in `pom.xml` for details).

(See direct link https://github.com/confluentinc/examples/tree/kafka-0.10.0.1-cp-3.0.1/kafka-streams#requirements-kafka)
