### ISSUE TITLE
kafka streams with scala

### ISSUE THREAD

**Issue by mazorigal** [confluentinc/examples#75]
Hi,

I know that basically I can use any java code in scala as well, but still would like to verify -- if I use kafka streams with scala,  should I be able to exploit the full functionality of kafka streams ? 

Also, is there an example how I can write serializer/deserializer for json data structure ? (in scala I would like actually to convert the json data to case class and visa versa, and until now I have usually used play-json for such tasks) 

Thanks,

**Comment by kv36** [comment]
Hi,
 I used spark and Its RDD's to perform analysis on the speed layer which usually deals with continuous streaming data. I used kafka queue's to store this data as an object. and then move it on to the cassandra. All this was implemented in scala, But most of the code syntax resembles java.(since i am even new to scala). I think the following code snippet can clear your question about its functionality.

import java.math.BigInteger
import java.util
import kafka.consumer.{ConsumerIterator, KafkaStream}
import org.apache.log4j.Logger
import org.apache.spark.SparkContext
import com.datastax.spark.connector.japi.CassandraJavaUtil.javaFunctions
import kafka.message.MessageAndMetadata
import org.apache.avro.generic.IndexedRecord
import org.apache.kafka.common.errors.SerializationException
import org.apache.spark.api.java.{JavaRDD, JavaSparkContext}
import org.apache.spark.rdd.RDD

class kartheekAddressConsumer(_kafkaStream: KafkaStream, _SparkContext: JavaSparkContext, _logger: Logger, _cassandraSchemaName: String, _cassandraTableName: String ) extends Runnable {
  override def run(): Unit = {
    val it: ConsumerIterator[_, _] = _kafkaStream.iterator
    while (it.hasNext) {
      val kartheekAddress: KartheekAddress = parseKartheekAddressFromStream(it)
      if (kartheekAddress != null) {
        val kartheekAddressList: util.ArrayList[KartheekAddress] = new util.ArrayList[KartheekAddress]
        kartheekAddressList.add(kartheekAddress)
       val customerAddressRdd: JavaRDD[CustomerAddress] = _SparkContext.parallelize(customerAddressList)

        // Save to Cassandra
   //i used row writer factory classes to save it to the cassandra.

        javaFunctions(kartheekAddressRdd).writerBuilder (_cassandraSchemaName, _cassandraTableName, new KartheekAddressDataWriterFactory).saveToCassandra ()
        _logger.debug("customerAddress: " + customerAddress.toString)

      }
    }
  }

// Here i am parsing the data and returning an object.(kartheekAddress)

def parseKartheekAddressFromStream(iterator: ConsumerIterator[_, _]) =
{
  val messageAndMetadata: MessageAndMetadata[_, _] = iterator.next
  val key: String = messageAndMetadata.key.asInstanceOf [String]
  val value: IndexedRecord = messageAndMetadata.message.asInstanceOf [IndexedRecord]
 val firstName: String = { if (value.get (3) != null) value.get(3).toString else null}
  val lastName: String = { if (value.get(4)!= null) value.get(4).toString else null}
  val company: String = { if (value.get(5)!= null) value.get(5).toString else null}
 val address1: String = { if (value.get(6)!= null) value.get(6).toString else null}
  val address2: String = {if (value.get(7)!= null) value.get(7).toString else null}
 val kartheekAddress: KartheekAddress = new KartheekAddress( firstName, lastName, company, address1, address2)
kartheekAddress
}

**Comment by miguno** [comment]
@mazorigal:

> I know that basically I can use any java code in scala as well, but still would like to verify -- if I use kafka streams with scala, should I be able to exploit the full functionality of kafka streams ? 

Yes, you have access to the full functionality of the Kafka Streams API when using Scala, just like when using Java.

> Also, is there an example how I can write serializer/deserializer for json data structure ? (in scala I would like actually to convert the json data to case class and visa versa, and until now I have usually used play-json for such tasks) 

There is an example JSON serde in the Apache Kafka code examples for Kafka Streams: https://github.com/apache/kafka/tree/trunk/streams/examples/src/main/java/org/apache/kafka/streams/examples/pageview.

Hope this helps!

**Comment by miguno** [comment]
@kv36 : I think the original question was about using Apache Kafka's own stream processing library (called Kafka Streams) to process data in Kafka (i.e. to use Kafka for processing Kafka data), rather than using a separate technology such as Spark.  Still, thanks for your feedback!

**Comment by mazorigal** [comment]
@kv36 thanks for the answer, but as miguno mentioned, I am asking specifically about kafka streams.

@miguno thanks for the answer. since I am not strong with java - the example in your link would eventually convert the java object (which reflect the json structure) to a string, meaning that the event submitted to kafka would be json string, or would it be serialized java object ?
In case it is serialized java object, is it mean that the deserializer must be also java with same json libs ?

**Comment by miguno** [comment]
> In case it is serialized java object, is it mean that the deserializer must be also java with same json libs ?

It doesn't need to be Java -- Scala will work just fine.  It just happens that the Kafka Streams library is implemented in Java, that's why most of the currently available examples are written in Java, too.

You can also use a different approach than the one shown in the Java JSON example.  For Scala, you may want to look at e.g. [Twitter Bijection](https://github.com/twitter/bijection) to convert between JSON and bytes.

**Comment by miguno** [comment]
> meaning that the event submitted to kafka would be json string, or would it be serialized java object

Kafka's messaging layer always works on bytes (byte arrays).  It's the application's responsibility to encode/decode "whatever you have" from/to bytes.  So the event submitted to Kafka would be bytes (that represent the JSON data).

**Comment by mazorigal** [comment]
so if I would like the messages in kafka would be programming language agnostic, I should serialize them as strings, or programming language agnostic SerDe such as avro, thrift ?

I know that avro is quite recommended, but when doing deserialization of  an avro message (for example) by python consumer and scala/java producer, could one still have issues due to how avro deserializer implemented in the different programming languages ? (we had issues reading kafka avro topic that consumed by Flume)

**Comment by miguno** [comment]
> I should serialize them as strings, or programming language agnostic SerDe such as avro, thrift ?

You should serialize as bytes.  Even strings would eventually need to be serialized to bytes.

> I know that avro is quite recommended, but when doing deserialization of an avro message (for example) by python consumer and scala/java producer, could one still have issues due to how avro deserializer implemented in the different programming languages ? (we had issues reading kafka avro topic that consumed by Flume) 

Avro works across any of its supported languages.  It could rather be an issues with the Avro integration that could cause such problems.  For example, when serializing a message, you can opt to include/embed the Avro schema that was used to Avro-serialize that message.  Or, you can opt not to include the Avro schema but rather include a "reference" (like an Avro schema id, which is what e.g. https://github.com/confluentinc/schema-registry/ and Confluent Avro serdes do).  Depending on which of these approaches you take, other tools may or may not work out of the box.

Does that help?

**Comment by mazorigal** [comment]
Thanks, thats help indeed.
just would like to clarify something small, by serializing as string, I meant to serialize the string to bytes, and then using any programming language in order to deserialize the bytes back to string, however if for example serializing java object to bytes, it would be quite hard to desirialize the message with python (for example).

**Comment by mjsax** [comment]
@mazorigal Can we close this? Or do you have more questions?
