### ISSUE TITLE
KafkaSream framework doesn't esnure to call punctuate() every time. 

### ISSUE THREAD

**Issue by deepakpengoria** [confluentinc/examples#86]
Problem statement : punctuate() in my processor class doesn't call everytime when we have multiple partition in the topic.

Reproducible steps : 
1- Create one topic with 100 partition
2- Keep sending messages to all 100 partitions with 100 unique keys for 1 or 2 hrs. 
3- You will notice that for couple of partitions, punctuate doesn't call. This is very severe issue. Please look into it.

**Comment by miguno** [comment]
@deepakpengoria: `punctuate()` is currently being a data-driven trigger that is based on event-time, not processing-time (processing-time = wall clock time).  Imagine, for example, you have configured punctuate to be called every `5 mins`.  If no input data arrives for 20 minutes, then punctuate will actually not be called at all, though I assume you would have expected it to be called 4 times, i.e. after 5, 10, 15, and 20 minutes have passed (and have passed in terms of processing-time).

We are currently having discussions in the community whether we want to change the semantics/behavior of `punctuate()`.  Originally in fact, it worked based on processing-time (i.e. it would have triggered 4 times in the example above), but the behavior was changed to the current one because users reported that they didn't like the original behavior and found it confusing. :-)

**Comment by deepakpengoria** [comment]
Thanks Minguno for quick response. 
Cann't we override punctuate() calling as per our need by writing some custom class? if yes then how?

**Comment by miguno** [comment]
@deepakpengoria: Unfortunately you can't do that right now.

**Comment by deepakpengoria** [comment]
@miguno : If punctuate() calling can't be overridden. Then, could you please help me to solve below problem - "I need to write the objects which are stored in state-store into topic if no events arrived in the partition for that key since last 30 minutes."

**Comment by miguno** [comment]
@deepakpengoria: If I may say so, could you please ask your last question in the [Kafka mailing lists](https://kafka.apache.org/contact)?  We try to keep the GitHub issues for this project related to the actual code examples provided here, and would rather encourage users to ask general "How do I implement my use case?" questions in the general mailing lists.

**Comment by harry9111985** [comment]
Hi @miguno  ... I am seeing inconsistent behaviour in the punctuate method , let me explain the issue 

The last batch of data is never qualified for processing by the punctuate method.

Use Case : 
a) I am getting data from a topic X .
b) Processor receives the data as on when the data is published by the KafkaProducer (each an every data is received on real time , no problem with that) . Data is sent with a delay of 1 sec.

c) Punctuate method is supposed to be called every 2 seconds while the data publishing takes place until the last data is published in the topic . However , the last message published in the topic is not processed by the punctuate method.

Comments received for processing : 12345 : Line Number : 9Line Text : 9 - **Log in the process method**

Comments processed 2017-08-22T12:44:52.697 - **Log in the punctuate method**

Comments received for processing : 4567 : Line Number : 9Line Text : 9 - - **Log in the process method**

Comments received for processing : 12345 : Line Number : 10Line Text : 10 - - **Log in the process method**
Comments received for processing : 4567 : Line Number : 10Line Text : 10 -- - **Log in the process method**

------ No Logs for the last batch to be processed by punctuate method ---------

I am using the below Kafka - Streams dependency : 

 //Kafka
    compile("org.apache.kafka:kafka-streams:0.11.0.0")


Regards,
Harish

**Comment by miguno** [comment]
Most likely this: http://docs.confluent.io/current/streams/faq.html#why-is-punctuate-not-called

Please note that this GH repository is not meant for general Q&A.  For questions such as the above, please follow "Want to ask a question" (#3) at https://github.com/confluentinc/examples/tree/3.3.0-post/kafka-streams#help.
